[2025-04-23 13:40:01,491] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-04-23 13:40:01,503] 107 dagshub - INFO - Accessing as Bharat34816
[2025-04-23 13:40:02,111] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/Bharat34816/networksecurity_mlops "HTTP/1.1 200 OK"
[2025-04-23 13:40:02,625] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-04-23 13:40:02,629] 107 dagshub - INFO - Initialized MLflow to track repo "Bharat34816/networksecurity_mlops"
[2025-04-23 13:40:02,631] 107 dagshub - INFO - Repository Bharat34816/networksecurity_mlops initialized!
[2025-04-23 13:40:09,098] 32 root - INFO - Start data Ingestion
[2025-04-23 13:40:15,644] 44 root - INFO - Successfully exported collection from MongoDB to DataFrame.
[2025-04-23 13:40:15,740] 60 root - INFO - Data exported to feature store at Artifacts\data_ingestion\feature_store\phisingData.csv.
[2025-04-23 13:40:15,746] 77 root - INFO - Performed train-test split on the DataFrame.
[2025-04-23 13:40:15,748] 86 root - INFO - Exporting train and test datasets to specified file paths.
[2025-04-23 13:40:15,853] 92 root - INFO - Train and test datasets exported successfully.
[2025-04-23 13:40:15,853] 114 root - INFO - Data ingestion completed successfully.
[2025-04-23 13:40:15,853] 35 root - INFO - Data Ingestion completed and artifact: DataIngestionArtifact(trained_file_path='Artifacts\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\data_ingestion\\ingested\\test.csv')
[2025-04-23 13:40:15,862] 44 root - INFO - Initiate the data Validation
[2025-04-23 13:40:15,968] 34 root - INFO - Required number of columns: 2
[2025-04-23 13:40:15,968] 35 root - INFO - Data frame has columns: 31
[2025-04-23 13:40:15,968] 34 root - INFO - Required number of columns: 2
[2025-04-23 13:40:15,969] 35 root - INFO - Data frame has columns: 31
[2025-04-23 13:40:15,971] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].
[2025-04-23 13:40:15,971] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].
[2025-04-23 13:40:15,971] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [82] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].].
[2025-04-23 13:40:15,971] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\app.py] line number [58] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [82] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].].].
