[2025-04-23 13:01:04,535] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-04-23 13:01:04,545] 107 dagshub - INFO - Accessing as Bharat34816
[2025-04-23 13:01:05,041] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/Bharat34816/networksecurity_mlops "HTTP/1.1 200 OK"
[2025-04-23 13:01:05,900] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-04-23 13:01:05,907] 107 dagshub - INFO - Initialized MLflow to track repo "Bharat34816/networksecurity_mlops"
[2025-04-23 13:01:05,910] 107 dagshub - INFO - Repository Bharat34816/networksecurity_mlops initialized!
[2025-04-23 13:01:10,772] 32 root - INFO - Start data Ingestion
[2025-04-23 13:02:32,523] 61 root - INFO - Performed train test split on the dataframe
[2025-04-23 13:02:32,524] 63 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[2025-04-23 13:02:32,524] 71 root - INFO - Exporting train and test file path.
[2025-04-23 13:02:32,601] 80 root - INFO - Exported train and test file path.
[2025-04-23 13:02:32,602] 35 root - INFO - Data Ingestion completed and artifact: DataIngestionArtifact(trained_file_path='Artifacts\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\data_ingestion\\ingested\\test.csv')
[2025-04-23 13:02:32,613] 44 root - INFO - Initiate the data Validation
[2025-04-23 13:02:32,709] 34 root - INFO - Required number of columns: 2
[2025-04-23 13:02:32,709] 35 root - INFO - Data frame has columns: 31
[2025-04-23 13:02:32,710] 34 root - INFO - Required number of columns: 2
[2025-04-23 13:02:32,710] 35 root - INFO - Data frame has columns: 31
[2025-04-23 13:02:32,711] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].
[2025-04-23 13:02:32,712] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].
[2025-04-23 13:02:32,712] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [82] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].].
[2025-04-23 13:02:32,712] 13 root - ERROR - Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\app.py] line number [58] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [82] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\pipeline\training_pipeline.py] line number [45] error message [Error occured in python file [C:\Users\bhara\OneDrive\Desktop\MLops\networksecurity\components\data_validation.py] line number [90] error message [Train dataframe does not contain all columns.
Test dataframe does not contain all columns.
].].].].
